steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--tag', '$_TAG', 
    '--build-arg', 'VITE_API_BASE_URL=$_VITE_API_BASE_URL', 
    '--build-arg', 'VITE_SUPABASE_URL=$_VITE_SUPABASE_URL', 
    '--build-arg', 'VITE_SUPABASE_ANON_KEY=$_VITE_SUPABASE_ANON_KEY', 
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_TAG']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'focusadhd-frontend',
    '--image', '$_TAG',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]

images: ['$_TAG']

substitutions:
  _TAG: 'us-central1-docker.pkg.dev/stable-hydra-492506-d4/focusadhd/frontend:v20260406'
  _VITE_API_BASE_URL: 'https://focusadhd-backend-740073113612.us-central1.run.app'
  _VITE_SUPABASE_URL: 'https://awcdikkmuqdtycpiuffu.supabase.co'
  _VITE_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Y2Rpa2ttdXFkdHljcGl1ZmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MjQ1MTUsImV4cCI6MjA5MDIwMDUxNX0.TRC2l2MKZPnZXjaR82-JTD6gwtsn0UAHK3Tubxm_tkA'
